import anthropic
import json
from app.config import ANTHROPIC_API_KEY

client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

def _call_claude(prompt: str, max_tokens: int = 2000) -> str:
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=max_tokens,
        messages=[{"role": "user", "content": prompt}]
    )
    response = message.content[0].text.strip()

    # Strip markdown code fences
    response = response.replace("```json", "").replace("```", "").strip()

    # Extract only the first valid JSON object
    # This handles cases where Claude adds extra text after the JSON
    
    brace_count = 0
    json_start = None
    json_end = None

    for i, char in enumerate(response):
        if char == "{":
            if json_start is None:
                json_start = i
            brace_count += 1
        elif char == "}":
            brace_count -= 1
            if brace_count == 0 and json_start is not None:
                json_end = i + 1
                break

    if json_start is not None and json_end is not None:
        response = response[json_start:json_end]

    return response


def summarize_recipe(transcript: str) -> dict:
    prompt = f"""You are a culinary assistant. Extract the recipe from this video transcript.

Transcript:
{transcript}

Respond in this exact JSON format and nothing else:
{{
  "title": "<recipe name>",
  "description": "<one line description of the dish>",
  "ingredients": ["<ingredient 1 with quantity>", "<ingredient 2 with quantity>"],
  "instructions": ["<step 1>", "<step 2>", "<step 3>"],
  "tips": ["<any tips or variations mentioned>"],
  "serving_size": "<how many people it serves if mentioned>"
}}"""

    try:
        response = _call_claude(prompt)
        return {"success": True, "content_type": "recipe", "output": json.loads(response)}
    except Exception as e:
        return {"success": False, "error": str(e)}


def summarize_coding(transcript: str) -> dict:
    prompt = f"""You are a senior software engineer. Analyze this coding tutorial transcript and extract structured information.

Transcript:
{transcript}

Respond in this exact JSON format and nothing else:
{{
  "title": "<what is being built>",
  "tech_stack": ["<technology 1>", "<technology 2>"],
  "summary": "<2-3 sentence overview of what the tutorial covers>",
  "steps": [
    {{
      "step": "<step title>",
      "explanation": "<what this step does>",
      "code": "<any code mentioned or explained, or empty string if none>"
    }}
  ],
  "key_concepts": ["<concept 1>", "<concept 2>"],
  "prerequisites": ["<prerequisite 1>", "<prerequisite 2>"]
}}"""

    try:
        response = _call_claude(prompt)
        return {"success": True, "content_type": "coding", "output": json.loads(response)}
    except Exception as e:
        return {"success": False, "error": str(e)}


def summarize_educational(transcript: str) -> dict:
    prompt = f"""You are an expert educator. Analyze this educational video transcript.

Transcript:
{transcript}

Respond in this exact JSON format and nothing else:
{{
  "title": "<topic of the video>",
  "subject": "<subject area e.g. History, Science, Finance, etc.>",
  "concise_summary": "<3-4 sentence summary of the entire video>",
  "key_points": ["<key point 1>", "<key point 2>", "<key point 3>"],
  "detailed_notes": "<full detailed notes from the video in paragraph form>",
  "important_terms": ["<term 1>", "<term 2>"],
  "takeaways": ["<main takeaway 1>", "<main takeaway 2>"]
}}"""

    try:
        response = _call_claude(prompt)
        return {"success": True, "content_type": "educational", "output": json.loads(response)}
    except Exception as e:
        return {"success": False, "error": str(e)}


def summarize_music(transcript: str) -> dict:
    prompt = f"""You are a music analyst. Analyze this music video transcript which contains song lyrics.

Important notes:
- The transcript is generated by speech-to-text so lyrics may have minor errors
- Do your best to reconstruct the most likely correct lyrics

Transcript:
{transcript}

Respond in this exact JSON format and nothing else:
{{
  "title": "<song title if identifiable, otherwise 'Unknown'>",
  "artist": "<artist name if identifiable, otherwise 'Unknown'>",
  "genre": "<likely genre e.g. Pop, Hip Hop, R&B, Rock>",
  "lyrics": "<full reconstructed lyrics from the transcript, formatted with line breaks>"
}}"""

    try:
        response = _call_claude(prompt, max_tokens=3000)
        return {"success": True, "content_type": "music", "output": json.loads(response)}
    except Exception as e:
        return {"success": False, "error": str(e)}

def summarize_general(transcript: str) -> dict:
    prompt = f"""You are a helpful assistant. Summarize this video transcript clearly.

Transcript:
{transcript}

Respond in this exact JSON format and nothing else:
{{
  "title": "<a suitable title for this video>",
  "summary": "<a clear 4-5 sentence summary of what this video is about>",
  "highlights": ["<highlight 1>", "<highlight 2>", "<highlight 3>"],
  "sentiment": "<positive, negative, or neutral>",
  "topics_covered": ["<topic 1>", "<topic 2>"]
}}"""

    try:
        response = _call_claude(prompt)
        return {"success": True, "content_type": "general", "output": json.loads(response)}
    except Exception as e:
        return {"success": False, "error": str(e)}


def summarize(transcript: str, content_type: str) -> dict:
    """
    Master router — calls the right summarizer based on content type.
    """
    router = {
        "recipe": summarize_recipe,
        "coding": summarize_coding,
        "educational": summarize_educational,
        "music": summarize_music,
        "general": summarize_general,
    }

    fn = router.get(content_type, summarize_general)
    return fn(transcript)